return {
	cmd = { "emmet-language-server", "--stdio" },
	root_markers = { "package.json", ".git" },
	filetypes = {
		"css",
		"eruby",
		"html",
		"htmldjango",
		"less",
		"sass",
		"scss",
		"pug",
		"blade",
		"vue",
		"javascriptreact",
		"typescriptreact",
		"svelte",
	},
	init_options = {
		includeLanguages = {
			javascript = "javascriptreact",
			typescript = "typescriptreact",
		},
		excludeLanguages = {},
		extensionsPath = {},
		preferences = {},
		showAbbreviationSuggestions = true,
		showExpandedAbbreviation = "always",
		showSuggestionsAsSnippets = false,
		syntaxProfiles = {},
		variables = {},
	},
}
